// Generado desde fixtures/ — presets §20 para la demo.
export interface DemoPreset { id: string; label: string; text: string }
export const DEMO_PRESETS: DemoPreset[] = [
  {
    "id": "fao",
    "label": "FAO AgrInnovation",
    "text": "FAO — Convocatoria AgrInnovation Challenge 2026\nAgricultura Inteligente y Resiliencia Climática en América Latina y el Caribe\n\nLa Organización de las Naciones Unidas para la Alimentación y la Agricultura (FAO), en el marco del Programa Regional de Seguridad Alimentaria para América Latina y el Caribe, lanza el reto internacional AgrInnovation Challenge 2026. La convocatoria busca soluciones tecnológicas innovadoras que combinen agricultura de precisión, monitoreo satelital, análisis de datos y enfoque en resiliencia climática para fortalecer los sistemas agroalimentarios en la región. Se priorizan soluciones que aborden la seguridad alimentaria, la adaptación al cambio climático y la sostenibilidad productiva en comunidades rurales vulnerables.\n\nPueden presentar propuestas: organizaciones sin fines de lucro legalmente constituidas, centros de investigación agropecuaria, universidades con programas de CTeI aplicada, y consorcios público-privados. Se valorarán especialmente las propuestas que integren componente tecnológico demostrable (monitoreo satelital, IoT agropecuario, trazabilidad digital), enfoque en seguridad alimentaria y escalabilidad regional. Las organizaciones participantes deben contar con experiencia comprobada de al menos tres (3) años en proyectos agropecuarios o de agricultura inteligente. Se requiere obligatoriamente un socio implementador local con presencia en el territorio de ejecución y carta de intención firmada.\n\nFinanciamiento disponible: hasta USD 250.000 por proyecto seleccionado, en modalidad de subvención no reembolsable. La convocatoria financia un máximo de 8 proyectos en esta ronda. Los proyectos deben ejecutarse en un plazo de 18 a 24 meses. Fecha de cierre para envío de concept notes: 30 de septiembre de 2026 (23:59 UTC-5). Los equipos seleccionados en la etapa de concept note serán invitados a presentar propuesta completa en noviembre de 2026. Contacto y postulación: agrinnovation2026@fao.org. Mayor información en: https://www.fao.org/lac/agrinnovation-challenge-2026.\n"
  },
  {
    "id": "fontagro",
    "label": "FONTAGRO Ganadería",
    "text": "FONTAGRO — Convocatoria Regional 2026\nInnovación en Ganadería Regenerativa y Sistemas Silvopastoriles para América Latina y el Caribe\n\nEl Fondo Regional de Tecnología Agropecuaria (FONTAGRO) abre su convocatoria regional 2026 orientada a proyectos de investigación aplicada e innovación en ganadería regenerativa, manejo sostenible de pasturas y sistemas silvopastoriles. El objetivo es generar y validar tecnologías y buenas prácticas que reduzcan la huella de carbono de los sistemas ganaderos, mejoren la biodiversidad y aumenten la productividad en el contexto del cambio climático, con énfasis en escalamiento regional y transferencia tecnológica entre países miembros de FONTAGRO.\n\nLa convocatoria está dirigida a instituciones de investigación agropecuaria, universidades con programas de agronomía o zootecnia, y organizaciones del sector ganadero con capacidad técnica demostrada. Es requisito obligatorio que cada propuesta cuente con al menos un (1) país socio miembro de FONTAGRO, además del país líder del proyecto; se aceptan consorcios de hasta cuatro países. Asimismo, es condición indispensable la participación de un centro de investigación acreditado (INIA, CIAT, CATIE, o equivalente nacional reconocido por FONTAGRO) en el consorcio proponente, con rol metodológico explícito en el diseño y validación de la intervención. Las propuestas deben incluir una teoría de cambio documentada que articule la cadena lógica desde las actividades hasta el impacto en sistemas ganaderos sostenibles y reducción de emisiones.\n\nMonto máximo financiable: USD 400.000 por proyecto, con posibilidad de cofinanciamiento del 30% por parte de los países socios. Duración del proyecto: 36 meses. Fecha límite de envío de propuesta completa: 28 de febrero de 2027. Se aceptarán cartas de interés hasta el 15 de enero de 2027. La evaluación técnica incluirá revisión de pares internacionales y entrevista con el equipo proponente. Documentos requeridos: propuesta técnica, presupuesto detallado, cartas de compromiso institucional de todos los socios y teoría de cambio. Más información: https://www.fontagro.org/convocatoria-ganaderia-regenerativa-2026.\n"
  },
  {
    "id": "minciencias",
    "label": "Minciencias 966",
    "text": "MINCIENCIAS — Términos de Referencia Convocatoria 966\nProyectos de Ciencia, Tecnología e Innovación (CTeI) con Alianzas Universidad-Empresa para el Sector Agropecuario\n\nEl Ministerio de Ciencia, Tecnología e Innovación (MINCIENCIAS) de Colombia abre la Convocatoria 966 de 2026 para la cofinanciación de proyectos de investigación aplicada, desarrollo tecnológico e innovación (I+D+i) en el sector agropecuario, con énfasis en tecnologías digitales, automatización, agricultura de precisión e inteligencia artificial para la cadena productiva. Esta convocatoria exige la conformación obligatoria de alianzas universidad-empresa: cada propuesta debe articular al menos una empresa del sector privado (agtech, agroalimentaria, o tecnológica) como beneficiaria directa de los resultados, y al menos una universidad o institución de educación superior acreditada como ejecutora principal con rol metodológico. También se admite la participación de entidades del estado con funciones de fomento agropecuario.\n\nLos indicadores mínimos de CTeI exigidos por proyecto son: al menos un (1) artículo científico publicado o sometido en revista indexada, un (1) producto de apropiación social del conocimiento, y registro de al menos una (1) innovación de proceso o producto ante la Superintendencia de Industria y Comercio o equivalente. Las propuestas deben presentar presupuesto detallado con aporte mínimo de contrapartida del 30% por parte de la empresa aliada, en recursos en efectivo o en especie valorados. El proyecto debe ejecutarse en el territorio colombiano. Las entidades elegibles son: grupos de investigación reconocidos y clasificados por MINCIENCIAS, universidades acreditadas, centros de investigación y desarrollo tecnológico, y empresas privadas con NIT vigente. No aplican personas naturales ni entidades extranjeras como ejecutoras principales.\n\nMonto máximo de cofinanciación MINCIENCIAS: COP 1.200.000.000 (mil doscientos millones de pesos colombianos) por proyecto. Duración máxima: 30 meses. Fecha límite de envío de propuestas al sistema MINCIENCIAS (SICYt): 10 de octubre de 2026 a las 23:59 hora Colombia (UTC-5). Requisitos documentales: formulario de propuesta, carta de aval institucional, acuerdos de alianza firmados, hoja de vida del equipo (CvLAC), presupuesto y cronograma. Preguntas y aclaraciones: convocatoria966@minciencias.gov.co. Términos de referencia completos: https://minciencias.gov.co/convocatoria-966-2026-agro-cti.\n"
  },
  {
    "id": "divfund",
    "label": "DIV Fund rural",
    "text": "DIV Fund — Request for Proposals (RFP) 2026\nPiloto de Impacto Rural: Evidencia Rigurosa, Escalabilidad y Costo-Efectividad en Agricultores Smallholder\n\nDIV Fund (Development Innovation Ventures — USAID) emite la presente Solicitud de Propuestas (RFP) para financiar pilotos de innovación en zonas rurales de América Latina con énfasis en agricultores smallholder (pequeños productores). Esta convocatoria busca soluciones probadas o prometedoras con potencial de escala, que cuenten con métricas de impacto claras, diseño de medición riguroso y análisis demostrable de costo-efectividad. DIV Fund prioriza intervenciones que puedan crecer a través de alianzas con gobiernos, actores privados o financiadores de mayor escala una vez validado el piloto.\n\nSon elegibles: organizaciones sin fines de lucro registradas, empresas sociales, cooperativas de agricultores, y organizaciones privadas con mandato social demostrable. Las propuestas deben indicar con precisión el número de beneficiarios directos e indirectos del piloto, la metodología de medición de impacto (preferiblemente ensayo controlado aleatorio o diseño cuasi-experimental), el análisis de costo por beneficiario y la ruta de escalabilidad (alianzas estratégicas previstas, modelo de financiamiento a escala, hoja de ruta de expansión geográfica o sectorial). Se valorará especialmente la integración de tecnología digital o satelital para monitoreo, verificación de impacto y trazabilidad de beneficiarios.\n\nMonto del financiamiento: entre USD 50.000 y USD 175.000 por proyecto, según etapa de evidencia (Stage 1: innovaciones nuevas; Stage 2: innovaciones con evidencia preliminar). Los fondos son no reembolsables. El piloto debe ejecutarse en un máximo de 24 meses. Número de beneficiarios esperado por proyecto: mínimo 200 hogares rurales directos. Fecha de cierre de RFP: 15 de agosto de 2026 (5:00 PM hora de Washington D.C.). Las organizaciones interesadas deben registrarse en el portal USAID Grants.gov antes del 8 de agosto de 2026. Contacto: div-fund-latam@usaid.gov. Consultar bases completas en: https://www.usaid.gov/div/rfp-rural-latam-2026.\n"
  },
  {
    "id": "secop",
    "label": "SECOP CAR ambiental",
    "text": "CORPORACIÓN AUTÓNOMA REGIONAL DE CUNDINAMARCA (CAR)\nPROCESO DE CONTRATACIÓN PÚBLICA — SECOP II\nObjeto: Prestación de servicios para el monitoreo ambiental satelital y terrestre de ecosistemas estratégicos en la jurisdicción CAR\nNúmero de proceso: CAR-LP-2026-047\n\nLa Corporación Autónoma Regional de Cundinamarca (CAR) convoca a personas jurídicas interesadas en prestar el servicio de monitoreo ambiental integral de ecosistemas estratégicos (humedales, páramos, zonas de recarga hídrica y corredores de biodiversidad) en la jurisdicción CAR. El contratista debe suministrar e implementar una plataforma tecnológica de monitoreo que combine imágenes satelitales multiespectrales (mínimo resolución 10 m), sensores IoT en campo, análisis de coberturas y alertas tempranas ante eventos de deforestación, incendios o degradación ambiental. La solución debe integrarse con el Sistema de Información Ambiental (SIAC) y ser interoperable con plataformas del IDEAM y el MADS.\n\nRequisitos habilitantes (jurídicos, financieros y técnicos): (1) Persona jurídica legalmente constituida en Colombia con objeto social relacionado con tecnologías ambientales, satelitales o sistemas de información geográfica; (2) Capacidad financiera mínima: índice de liquidez ≥ 1,5 e índice de endeudamiento ≤ 60%, certificados en estados financieros del año 2025; (3) Experiencia habilitante: al menos dos (2) contratos ejecutados en los últimos cinco (5) años por objeto igual o similar (monitoreo ambiental, teledetección satelital, o sistemas de información geográfica para entidades públicas), con valor acumulado no inferior a COP 800.000.000 (ochocientos millones de pesos); (4) Certificación de sistema de gestión de calidad ISO 9001 vigente o equivalente.\n\nPresupuesto oficial estimado: COP 1.500.000.000 (mil quinientos millones de pesos colombianos), IVA incluido. Plazo de ejecución del contrato: 12 meses prorrogables. Modalidad de selección: Licitación Pública. Fecha límite para presentación de ofertas: 5 de noviembre de 2026 a las 3:00 p.m. (hora Colombia). Las propuestas deben presentarse exclusivamente a través de SECOP II (https://www.secop.gov.co). El pliego de condiciones definitivo estará disponible en SECOP II a partir del 15 de septiembre de 2026. Audiencia de aclaración de pliegos: 29 de septiembre de 2026. Contacto: licitaciones@car.gov.co. Referencia del proceso en SECOP II: CAR-LP-2026-047.\n"
  }
]
